name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Generate Log File
        run: |
          echo "$(date --iso-8601=minutes)" > /tmp/log.txt
          echo "Eran Krakovsky, Noa Landau" >> /tmp/log.txt
      # -
      #   name: Build and export
      #   uses: docker/build-push-action@v4
      #   continue-on-error: true
      #   with:
      #     context: .
      #     tags: cloud-hw3:latest
      #     outputs: type=docker,dest=/tmp/cloud-hw3.tar
      - 
        name: build image
        continue-on-error: true
        run: |
          if [ docker build -t cloud-hw3:latest . -eq 0 ]; then
          echo "image successfully built" >> /tmp/log.txt
          docker save cloud-hw3:latest /tmp/cloud-hw3.tar
          else
          echo "image not able to be built" >> /tmp/log.txt
          fi
      -
        name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: results
            path: |
              /tmp/cloud-hw3.tar
              /tmp/log.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: results
          path: /tmp
      -
        name: Load image
        run: |
          docker load --input /tmp/cloud-hw3.tar
      -
        name: Run container
        run: |
          docker run --rm -d -p 8000:5001 cloud-hw3:latest
          if [ $? -eq 0 ]; then
            echo "Container up and running" >> /tmp/log.txt
          else
            echo "Container failed to run" >> /tmp/log.txt
          fi
      - 
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - 
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      -
        name: Run tests
        continue-on-error: true
        run: |
          if [ pytest tests/tests.py -v > /tmp/assn3_test_results.txt -eq 0 ]; then
            echo "tests succeeded" >> /tmp/log.txt
          else
            echo "tests failed" >> /tmp/log.txt
          fi
      -
        name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: results
            path: |
              /tmp/assn3_test_results.txt
              /tmp/log.txt